-- Terminologie « voyage d’affaires / agence » + libellés type de voyageur (FR + AR)
INSERT INTO ui_translations (locale, msg_key, msg_value) VALUES
('fr', 'login.brandTitle', 'Agence voyage'),
('ar', 'login.brandTitle', 'وكالة سفر'),
('fr', 'login.brandTagline', 'Espace agence — accompagner chaque voyageur avec sérénité.'),
('ar', 'login.brandTagline', 'مساحة الوكالة — مرافقة كل مسافر باطمئنان.'),
('fr', 'login.heroMotto', 'Groupes, dossiers clients et parrainage — un même lieu pour votre agence.'),
('ar', 'login.heroMotto', 'المجموعات وملفات العملاء والإحالة — مكان واحد لوكالتك.'),
('fr', 'nav.pilgrims', 'Voyageurs'),
('ar', 'nav.pilgrims', 'المسافرون'),
('fr', 'nav.groups', 'Groupes de voyage'),
('ar', 'nav.groups', 'مجموعات السفر'),
('fr', 'nav.group.participants', 'Voyageurs & groupes'),
('ar', 'nav.group.participants', 'المسافرون والمجموعات'),
('fr', 'pilgrims.listTitle', 'Voyageurs'),
('ar', 'pilgrims.listTitle', 'المسافرون'),
('fr', 'pilgrims.listSubtitle', 'Gérez les dossiers voyageurs de vos groupes'),
('ar', 'pilgrims.listSubtitle', 'إدارة ملفات المسافرين في مجموعاتك'),
('fr', 'pilgrims.add', 'Ajouter un voyageur'),
('ar', 'pilgrims.add', 'إضافة مسافر'),
('fr', 'pilgrims.searchPh', 'Nom, passeport, nationalité…'),
('ar', 'pilgrims.searchPh', 'الاسم، الجواز، الجنسية…'),
('fr', 'pilgrims.searchAria', 'Rechercher un voyageur'),
('ar', 'pilgrims.searchAria', 'البحث عن مسافر'),
('fr', 'pilgrims.loading', 'Chargement des voyageurs…'),
('ar', 'pilgrims.loading', 'جاري تحميل المسافرين…'),
('fr', 'pilgrims.empty', 'Aucun voyageur'),
('ar', 'pilgrims.empty', 'لا يوجد مسافرون'),
('fr', 'pilgrims.emptyDesc', 'Ajoutez un voyageur pour commencer.'),
('ar', 'pilgrims.emptyDesc', 'أضف مسافرًا للبدء.'),
('fr', 'pilgrims.deleteConfirm', 'Supprimer ce voyageur ?'),
('ar', 'pilgrims.deleteConfirm', 'حذف هذا المسافر؟'),
('fr', 'pilgrims.deleted', 'Voyageur supprimé'),
('ar', 'pilgrims.deleted', 'تم حذف المسافر'),
('fr', 'list.count.pilgrims.one', '{{count}} voyageur'),
('ar', 'list.count.pilgrims.one', '{{count}} مسافر'),
('fr', 'list.count.pilgrims.many', '{{count}} voyageurs'),
('ar', 'list.count.pilgrims.many', '{{count}} مسافرين'),
('fr', 'stats.pilgrims', 'Voyageurs'),
('ar', 'stats.pilgrims', 'المسافرون'),
('fr', 'groupTabs.pilgrims', 'Voyageurs'),
('ar', 'groupTabs.pilgrims', 'المسافرون'),
('fr', 'err.pilgrimsLoad', 'Erreur chargement voyageurs'),
('ar', 'err.pilgrimsLoad', 'خطأ في تحميل المسافرين'),
('fr', 'pilgrims.mo3tamir.pageTitleNew', 'Nouveau voyageur'),
('ar', 'pilgrims.mo3tamir.pageTitleNew', 'مسافر جديد'),
('fr', 'pilgrims.mo3tamir.pageTitleEdit', 'Modifier le voyageur'),
('ar', 'pilgrims.mo3tamir.pageTitleEdit', 'تعديل المسافر'),
('fr', 'pilgrims.mo3tamir.heroLead', 'Renseignez le dossier : mode individuel ou famille. Les champs obligatoires sont indiqués.'),
('ar', 'pilgrims.mo3tamir.heroLead', 'أكمل الملف: فردي أو عائلة. الحقول الإلزامية موضحة.'),
('fr', 'pilgrims.mo3tamir.createPilgrim', 'Créer le voyageur'),
('ar', 'pilgrims.mo3tamir.createPilgrim', 'إنشاء المسافر'),
('fr', 'pilgrims.mo3tamir.createFamily', 'Créer {{n}} voyageurs'),
('ar', 'pilgrims.mo3tamir.createFamily', 'إنشاء {{n}} مسافرين'),
('fr', 'pilgrims.mo3tamir.familyCreated', '{{n}} voyageurs créés avec succès.'),
('ar', 'pilgrims.mo3tamir.familyCreated', 'تم إنشاء {{n}} مسافرين بنجاح.'),
('fr', 'pilgrims.mo3tamir.familyDocsHint', 'En mode famille, ajoutez les pièces jointes depuis la fiche de chaque voyageur après création (liste des voyageurs).'),
('ar', 'pilgrims.mo3tamir.familyDocsHint', 'في وضع العائلة، أضف المرفقات من ملف كل مسافر بعد الإنشاء.'),
('fr', 'pilgrims.mo3tamir.travelerType', 'Type de voyageur'),
('ar', 'pilgrims.mo3tamir.travelerType', 'نوع المسافر'),
('fr', 'pilgrims.travelerType.PILGRIM', 'Pèlerin'),
('ar', 'pilgrims.travelerType.PILGRIM', 'معتمر / حاج'),
('fr', 'pilgrims.travelerType.LEISURE', 'Vacances'),
('ar', 'pilgrims.travelerType.LEISURE', 'عطلة'),
('fr', 'pilgrims.travelerType.WORK', 'Travail'),
('ar', 'pilgrims.travelerType.WORK', 'عمل'),
('fr', 'pilgrims.travelerType.BUSINESS', 'Affaires'),
('ar', 'pilgrims.travelerType.BUSINESS', 'أعمال'),
('fr', 'pilgrims.travelerType.OTHER', 'Autre'),
('ar', 'pilgrims.travelerType.OTHER', 'أخرى'),
('fr', 'pilgrims.col.travelerType', 'Type'),
('ar', 'pilgrims.col.travelerType', 'النوع'),
('fr', 'pilgrims.documents.dialogTitle', 'Documents du voyageur'),
('ar', 'pilgrims.documents.dialogTitle', 'مستندات المسافر'),
('fr', 'pilgrims.documents.empty', 'Aucun document pour ce voyageur.'),
('ar', 'pilgrims.documents.empty', 'لا توجد مستندات لهذا المسافر.'),
('fr', 'pilgrims.form.uploadZoneDesc', 'Les fichiers sont liés au dossier du voyageur : ajoutez-les ci-dessous, ils seront envoyés automatiquement dès que vous aurez cliqué sur « Créer le voyageur ».'),
('ar', 'pilgrims.form.uploadZoneDesc', 'الملفات مرتبطة بملف المسافر: أضفها هنا وسترسل تلقائياً عند النقر على «إنشاء المسافر».'),
('fr', 'pilgrims.form.documentsQueuedPartialFail', 'Voyageur créé, mais l’envoi d’au moins une pièce a échoué. Vous pouvez les ajouter depuis cette fiche.'),
('ar', 'pilgrims.form.documentsQueuedPartialFail', 'تم إنشاء المسافر لكن فشل رفع بعض الملفات.'),
('fr', 'pilgrims.sponsorship.lead', 'Indiquez qui oriente ce voyageur. Si le parrain est un autre client enregistré, des points seront crédités sur son dossier.'),
('ar', 'pilgrims.sponsorship.lead', 'حدد من يوجه هذا المسافر.'),
('fr', 'pilgrims.sponsorship.typePilgrim', 'Voyageur (dossier existant)'),
('ar', 'pilgrims.sponsorship.typePilgrim', 'مسافر (ملف موجود)'),
('fr', 'pilgrims.sponsorship.searchPilgrim', 'Voyageur parrain'),
('ar', 'pilgrims.sponsorship.searchPilgrim', 'مسافر مرجعي'),
('fr', 'pilgrims.sponsorship.searchHint', 'Saisissez au moins 2 caractères. Les points de parrainage sont attribués uniquement si vous sélectionnez un voyageur existant.'),
('ar', 'pilgrims.sponsorship.searchHint', 'أدخل حرفين على الأقل.'),
('fr', 'pilgrims.sponsorship.errorSelectReferrer', 'Sélectionnez un voyageur dans la liste ou choisissez un autre type de parrain.'),
('ar', 'pilgrims.sponsorship.errorSelectReferrer', 'اختر مسافراً من القائمة.'),
('fr', 'pilgrims.sponsorship.referrerName', 'Voyageur parrain'),
('ar', 'pilgrims.sponsorship.referrerName', 'المسافر المرجعي'),
('fr', 'referral.tabPilgrims', 'Programme voyageurs'),
('ar', 'referral.tabPilgrims', 'برنامج المسافرين'),
('fr', 'referral.pointsRule', 'Chaque fois qu’un nouveau voyageur est enregistré avec un parrain de type « Voyageur », le parrain reçoit {{n}} point(s).'),
('ar', 'referral.pointsRule', 'عند تسجيل مسافر جديد بمرجع من نوع «مسافر» يحصل المرجع على {{n}} نقطة.'),
('fr', 'referral.userTabIntro', 'Partagez votre code ou lien pour inviter des personnes à créer un compte sur la plateforme (hors filleuls voyageurs).'),
('ar', 'referral.userTabIntro', 'شارك رمزك أو رابطك لدعوة أنشطة حسابات على المنصة.'),
('fr', 'referral.tiers.introTitle', 'Fidélité voyageurs'),
('ar', 'referral.tiers.introTitle', 'ولاء المسافرين'),
('fr', 'groups.tab.pilgrims', 'Voyageurs'),
('ar', 'groups.tab.pilgrims', 'المسافرون'),
('fr', 'groups.pilgrims.pilgrim', 'Voyageur'),
('ar', 'groups.pilgrims.pilgrim', 'مسافر'),
('fr', 'groups.pilgrims.noneFound', 'Aucun voyageur trouvé'),
('ar', 'groups.pilgrims.noneFound', 'لم يُعثر على مسافر'),
('fr', 'groups.pilgrims.tableEmpty', 'Aucun voyageur ne correspond à la recherche.'),
('ar', 'groups.pilgrims.tableEmpty', 'لا يطابق البحث أي مسافر.'),
('fr', 'pilgrims.notif.notFound', 'Voyageur introuvable'),
('ar', 'pilgrims.notif.notFound', 'المسافر غير موجود'),
('fr', 'pilgrims.notif.created', 'Voyageur créé'),
('ar', 'pilgrims.notif.created', 'تم إنشاء المسافر'),
('fr', 'pilgrims.notif.updated', 'Voyageur modifié'),
('ar', 'pilgrims.notif.updated', 'تم تعديل المسافر'),
('fr', 'pilgrims.detail.title', 'Détail voyageur'),
('ar', 'pilgrims.detail.title', 'تفاصيل المسافر'),
('fr', 'pilgrims.detail.back', 'Retour aux voyageurs'),
('ar', 'pilgrims.detail.back', 'العودة إلى المسافرين'),
('fr', 'pilgrims.detail.deleteConfirm', 'Supprimer ce voyageur ? Cette action est irréversible.'),
('ar', 'pilgrims.detail.deleteConfirm', 'حذف هذا المسافر؟ لا يمكن التراجع.'),
('fr', 'pilgrims.detail.deleted', 'Voyageur supprimé'),
('ar', 'pilgrims.detail.deleted', 'تم حذف المسافر')
ON CONFLICT (locale, msg_key) DO UPDATE SET msg_value = EXCLUDED.msg_value;
